### ISSUE TITLE
Increase minimum version of @auth0/auth0-spa-js

### ISSUE THREAD

**Issue by JasonWeinzierl** [auth0/auth0-angular#753]
### Checklist

- [x] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I recently upgraded this library from 2.3 to 2.4, but it caused compilation errors.  I discovered this was because I have version 2.1.3 of `@auth0/auth0-spa-js` installed.  After upgrading `@auth0/auth0-spa-js` to 2.11.0, my compilation started working again.  I don't have `@auth0/auth0-spa-js` referenced as a direct dependency, so I had to manually edit my yarn.lock to force the upgrade.

### Describe the ideal solution

Increase the minimum version of `@auth0/auth0-spa-js` so that users without a direct reference on it still pull in a compatible version.

### Alternatives and current workarounds

Directly install `@auth0/auth0-spa-js` and bump it myself, or delete my `yarn.lock` and let it re-generate.
