### ISSUE TITLE
RedirectLoginOptions is not generic (1.8.1)

### ISSUE THREAD

**Issue by frasermclean** [auth0/auth0-angular#265]
After updating to 1.8.1 (was previously on 1.8.0) I get the following issues during build: 

```
Error: node_modules/@auth0/auth0-angular/lib/auth.service.d.ts:57:33 - error TS2315: Type 'RedirectLoginOptions' is not generic.

57     loginWithRedirect(options?: RedirectLoginOptions<TAppState>): Observable<void>;
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@auth0/auth0-angular/lib/auth.service.d.ts:133:54 - error TS2315: Type 'RedirectLoginResult' is not generic.

133     handleRedirectCallback(url?: string): Observable<RedirectLoginResult<TAppState>>;
```

**Comment by frederikprijck** [comment]
Hey,

This should be resolved in the next release, which I am planning somewhere this week.

For now, you should be able to work around this by ensuring you bring in the latest `@auth0/auth0-spa-js`, either by running `npm install` (after clearing `node_modules`) or by explicitly using `npm install @auth0/auth0-spa-js`.

Let me know if this does not work for you!

**Comment by frederikprijck** [comment]
I just released a patched version, can you let me know if running `npm i @auth0/auth0-angular@latest` solves it ?

**Comment by frasermclean** [comment]
Yeah seems to work now, thanks!
